export const ProjectColumns = [
  { key: 'title', label: 'Title', _props: { scope: 'col', align: 'center' } },
  { key: 'thumb', label: 'Thumb', _props: { scope: 'col' } },
  { key: 'img', label: 'Img', _props: { scope: 'col' } },
  { key: 'services', label: 'Services', _props: { scope: 'col' } },
  { key: 'industry', label: 'Industry', _props: { scope: 'col' } },
  { key: 'platform', label: 'Platform', _props: { scope: 'col' } },
  { key: 'overview', label: 'Overview', _props: { scope: 'col' } },
  { key: 'link', label: 'Link', _props: { scope: 'col' } },
  { key: 'team', label: 'Team', _props: { scope: 'col' } },
  { key: 'duration', label: 'Duration', _props: { scope: 'col' } },
  { key: 'stacks', label: 'Stacks', _props: { scope: 'col' } },
  { key: 'result', label: 'Result', _props: { scope: 'col' } },
  { key: 'duration', label: 'Duration', _props: { scope: 'col' } },
  { key: 'status', label: 'Status', _props: { scope: 'col' } },
  { key: 'action', label: 'action', _props: { scope: 'col' } },
]
